language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t froggyking/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true froggyking/react-test npm test
after_success:
  - docker build -t froggyking/multi-client ./client
  - docker build -t froggyking/multi-nginx ./nginx
  - docker build -t froggyking/multi-server ./server
  - docker build -t froggyking/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push froggyking/multi-client
  - docker push froggyking/multi-nginx
  - docker push froggyking/multi-server
  - docker push froggyking/multi-worker